name: "Triangulum CLI Scan"
author: "Akhil Reni"
description: "Scan the repo for security Vulnerabilities using publicly accessible scanners"

inputs:
  rules:
    description: "Rules to check against for vulnerabilities, comma seprated(c2,m3) means only 2 critical & 3 medium vulnerabilities are allowed"
    required: false
  download_url:
    description: "URL to download Triangulum executable from"
    required: true
  send_to_strobes:
    description: "Send bugs in scan to Strobes using Strobes client"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
